// <auto-generated />
using System;
using Api.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20230907234642_Uf_Countrys_Cep")]
    partial class UfCountrysCep
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Api.Domain.Entities.CepEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Cep")
                        .IsUnique();

                    b.HasIndex("CountryId");

                    b.ToTable("Cep", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Entities.CountryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CodIBGE")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<Guid>("UfId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CodIBGE")
                        .IsUnique();

                    b.HasIndex("UfId");

                    b.ToTable("Country", (string)null);
                });

            modelBuilder.Entity("Api.Domain.Entities.UfEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.ToTable("Uf", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22ffbd18-cdb9-45cc-97b0-51e97700bf71"),
                            Abbreviation = "AC",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7246),
                            Name = "Acre"
                        },
                        new
                        {
                            Id = new Guid("7cc33300-586e-4be8-9a4d-bd9f01ee9ad8"),
                            Abbreviation = "AL",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7250),
                            Name = "Alagoas"
                        },
                        new
                        {
                            Id = new Guid("cb9e6888-2094-45ee-bc44-37ced33c693a"),
                            Abbreviation = "AM",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7252),
                            Name = "Amazonas"
                        },
                        new
                        {
                            Id = new Guid("409b9043-88a4-4e86-9cca-ca1fb0d0d35b"),
                            Abbreviation = "AP",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7253),
                            Name = "Amapá"
                        },
                        new
                        {
                            Id = new Guid("5abca453-d035-4766-a81b-9f73d683a54b"),
                            Abbreviation = "BA",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7255),
                            Name = "Bahia"
                        },
                        new
                        {
                            Id = new Guid("5ff1b59e-11e7-414d-827e-609dc5f7e333"),
                            Abbreviation = "CE",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7256),
                            Name = "Ceará"
                        },
                        new
                        {
                            Id = new Guid("bd08208b-bfca-47a4-9cd0-37e4e1fa5006"),
                            Abbreviation = "DF",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7258),
                            Name = "Distrito Federal"
                        },
                        new
                        {
                            Id = new Guid("c623f804-37d8-4a19-92c1-67fd162862e6"),
                            Abbreviation = "ES",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7260),
                            Name = "Espírito Santo"
                        },
                        new
                        {
                            Id = new Guid("837a64d3-c649-4172-a4e0-2b20d3c85224"),
                            Abbreviation = "GO",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7261),
                            Name = "Goiás"
                        },
                        new
                        {
                            Id = new Guid("57a9e9f7-9aea-40fe-a783-65d4feb59fa8"),
                            Abbreviation = "MA",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7262),
                            Name = "Maranhão"
                        },
                        new
                        {
                            Id = new Guid("27f7a92b-1979-4e1c-be9d-cd3bb73552a8"),
                            Abbreviation = "MG",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7264),
                            Name = "Minas Gerais"
                        },
                        new
                        {
                            Id = new Guid("3739969c-fd8a-4411-9faa-3f718ca85e70"),
                            Abbreviation = "MS",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7265),
                            Name = "Mato Grosso do Sul"
                        },
                        new
                        {
                            Id = new Guid("29eec4d3-b061-427d-894f-7f0fecc7f65f"),
                            Abbreviation = "MT",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7266),
                            Name = "Mato Grosso"
                        },
                        new
                        {
                            Id = new Guid("8411e9bc-d3b2-4a9b-9d15-78633d64fc7c"),
                            Abbreviation = "PA",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7268),
                            Name = "Pará"
                        },
                        new
                        {
                            Id = new Guid("1109ab04-a3a5-476e-bdce-6c3e2c2badee"),
                            Abbreviation = "PB",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7269),
                            Name = "Paraíba"
                        },
                        new
                        {
                            Id = new Guid("ad5969bd-82dc-4e23-ace2-d8495935dd2e"),
                            Abbreviation = "PE",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7271),
                            Name = "Pernambuco"
                        },
                        new
                        {
                            Id = new Guid("f85a6cd0-2237-46b1-a103-d3494ab27774"),
                            Abbreviation = "PI",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7272),
                            Name = "Piauí"
                        },
                        new
                        {
                            Id = new Guid("1dd25850-6270-48f8-8b77-2f0f079480ab"),
                            Abbreviation = "PR",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7273),
                            Name = "Paraná"
                        },
                        new
                        {
                            Id = new Guid("43a0f783-a042-4c46-8688-5dd4489d2ec7"),
                            Abbreviation = "RJ",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7275),
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = new Guid("542668d1-50ba-4fca-bbc3-4b27af108ea3"),
                            Abbreviation = "RN",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7276),
                            Name = "Rio Grande do Norte"
                        },
                        new
                        {
                            Id = new Guid("924e7250-7d39-4e8b-86bf-a8578cbf4002"),
                            Abbreviation = "RO",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7278),
                            Name = "Rondônia"
                        },
                        new
                        {
                            Id = new Guid("9fd3c97a-dc68-4af5-bc65-694cca0f2869"),
                            Abbreviation = "RR",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7279),
                            Name = "Roraima"
                        },
                        new
                        {
                            Id = new Guid("88970a32-3a2a-4a95-8a18-2087b65f59d1"),
                            Abbreviation = "RS",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7280),
                            Name = "Rio Grande do Sul"
                        },
                        new
                        {
                            Id = new Guid("b81f95e0-f226-4afd-9763-290001637ed4"),
                            Abbreviation = "SC",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7282),
                            Name = "Santa Catarina"
                        },
                        new
                        {
                            Id = new Guid("fe8ca516-034f-4249-bc5a-31c85ef220ea"),
                            Abbreviation = "SE",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7283),
                            Name = "Sergipe"
                        },
                        new
                        {
                            Id = new Guid("e7e416de-477c-4fa3-a541-b5af5f35ccf6"),
                            Abbreviation = "SP",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7284),
                            Name = "São Paulo"
                        },
                        new
                        {
                            Id = new Guid("971dcb34-86ea-4f92-989d-064f749e23c9"),
                            Abbreviation = "TO",
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7286),
                            Name = "Tocantins"
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("683bb91f-d0f8-4579-9221-797f48cd2b07"),
                            CreateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7121),
                            Email = "adm@email.com",
                            Name = "Administrator",
                            UpdateAt = new DateTime(2023, 9, 7, 23, 46, 42, 157, DateTimeKind.Utc).AddTicks(7126)
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.CepEntity", b =>
                {
                    b.HasOne("Api.Domain.Entities.CountryEntity", "Country")
                        .WithMany("Ceps")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Api.Domain.Entities.CountryEntity", b =>
                {
                    b.HasOne("Api.Domain.Entities.UfEntity", "Uf")
                        .WithMany("Countries")
                        .HasForeignKey("UfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uf");
                });

            modelBuilder.Entity("Api.Domain.Entities.CountryEntity", b =>
                {
                    b.Navigation("Ceps");
                });

            modelBuilder.Entity("Api.Domain.Entities.UfEntity", b =>
                {
                    b.Navigation("Countries");
                });
#pragma warning restore 612, 618
        }
    }
}
